dist: trusty
group: edge
sudo: true
language: java
install: true
before_install:
  - echo $TRAVIS_JDK_VERSION
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      chmod +x wildfly-install.sh;
      sudo ./wildfly-install.sh;
    fi
script:
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      mvn wildfly:deploy;
      content=$(curl -L localhost:28080/TestProject);
      echo $content;
    else
      mvn install;
    fi
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8
matrix:
  include:
  - dist: precise
    jdk: oraclejdk7
  - jdk: oraclejdk9
    addons:
      apt:
        packages:
          - oracle-java9-installer

cache:
  apt: true
  packages: true
  directories:
  - .autoconf
  - $HOME/.m2