dist: trusty
group: edge
sudo: true
language: java
install: true
services:
  - mysql
before_install:
  - echo $TRAVIS_JDK_VERSION
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      chmod +x wildfly-install.sh;
      sudo ./wildfly-install.sh;
    fi
script:
  - set -e;
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      mysqladmin -u root create iui;
      mysqlshow --user=root iui;
      mvn -f pomsql.xml install;
      mvn -f pomsql.xml wildfly:deploy;
      content=$(curl -L localhost:8080/TestProject);
      echo $content;
      content=$(curl -L localhost:8080/TestProject/create);
      echo $content;
      content=$(curl -L localhost:8080/TestProject/show/1);
      echo $content;
    else
      mvn -f pom.xml install;
    fi
  - set +e;
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8
matrix:
  include:
  - dist: precise
    jdk: oraclejdk7
  - jdk: oraclejdk9
    addons:
      apt:
        packages:
          - oracle-java9-installer

cache:
  apt: true
  packages: true
  directories:
  - .autoconf
  - $HOME/.m2