dist: trusty
group: edge
sudo: true
language: java
install: true
services:
  - mysql
before_install:
  - echo $TRAVIS_JDK_VERSION
  - sudo apt-get update
  - sudo apt-get install nodejs
<<<<<<< HEAD
  - npm install --save-dev @angular/cli@latest
=======
  - sudo apt-get install npm@3.10.10
  - npm install -g @angular/cli@1.6.4
>>>>>>> add73c4a651694d62f627bfc0c25650cafc8b3b3
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      chmod +x wildfly-install.sh;
      sudo ./wildfly-install.sh;
    fi
script:
  - set -e;
  - if [ $TRAVIS_JDK_VERSION = "oraclejdk8" ] || [ $TRAVIS_JDK_VERSION = "openjdk8" ]; then
      mysqladmin -u root create iui;
      mysqlshow --user=root iui;
      mvn -f pomtravis.xml wildfly:deploy-artifact@deploy-mysql-driver;
      mvn -f pomtravis.xml wildfly:add-resource@add-datasource;
      mvn -f pomtravis.xml wildfly:deploy;
      content=$(curl  -L localhost:8080/TestProject/api);
      echo $content;
      content=$(curl  -L localhost:8080/TestProject/api/create);
      echo $content;
      content=$(curl  -L localhost:8080/TestProject/api/show/1);
      echo $content;
      content=$(curl  -L localhost:8080/TestProject/ng/);
      echo $content;
    else
      mvn -f pomtravis.xml verify;
    fi
  - set +e;
jdk:
  - oraclejdk8
  - openjdk8
matrix:
  include:
  - jdk: oraclejdk9
    addons:
      apt:
        packages:
          - oracle-java9-installer

cache:
  apt: true
  packages: true
  directories:
  - .autoconf
  - $HOME/.m2